import crypto from 'crypto';
import { connectToDatabase } from './shared/db.js';
import { calculateAchievements, getAllAchievementsStatus } from './shared/achievements_config.js';
import { getISTISOString, getISTLogPrefix } from './shared/timezone.js';
import { deserializeSyllabus, serializeSyllabus, loadTemplate } from './shared/syllabus.js';
import { normalizeUrl } from '../src/shared/normalize.js';
import { resolveUser, hashSyncId } from './shared/auth.js';

export default async function handler(req, res) {
  // Enforce global request body size limit of 2MB to protect MongoDB and Vercel functions
  const contentLength = req.headers['content-length'] ? parseInt(req.headers['content-length'], 10) : 0;
  if (contentLength > 2 * 1024 * 1024 || (req.body && JSON.stringify(req.body).length > 2 * 1024 * 1024)) {
    return res.status(413).json({ error: 'Payload too large (limit is 2MB)' });
  }

  try {
    const db = await connectToDatabase();
    const collection = db.collection('users');

    if (req.method === 'GET') {
      const rawSyncId = req.query.syncId;
      if (!rawSyncId || typeof rawSyncId !== 'string') {
        return res.status(400).json({ error: 'Invalid or missing syncId' });
      }
      const syncId = String(rawSyncId).trim();
      if (!syncId) return res.status(400).json({ error: 'syncId cannot be empty' });

      const userDoc = await resolveUser(db, syncId);
      let sessionToken = null;

      if (userDoc) {
        if (userDoc.logoutTimestamp) {
          console.log(`[Vinyas Inactivity] User ${userDoc.syncId} logged back in / active. Resetting inactivity countdown and warning flags. Previous logoutTimestamp: ${userDoc.logoutTimestamp}`);
        }
        // Clear logout status because user is active
        await collection.updateOne({ syncId: userDoc.syncId }, { $unset: { logoutTimestamp: "", alertSent: "" } });
        userDoc.logoutTimestamp = null;
        userDoc.alertSent = false;
        
        // If lookup was done via a plaintext syncId, generate a new session token
        if (syncId.startsWith('vny_sec_')) {
          sessionToken = 'vny_sess_' + crypto.randomBytes(24).toString('hex');
          const newSession = {
            token: sessionToken,
            createdAt: new Date().toISOString(),
            lastUsedAt: new Date().toISOString()
          };
          await collection.updateOne(
            { syncId: userDoc.syncId },
            { $push: { sessions: newSession } }
          );
        }

        // Reconstruct the full syllabus data before calculating achievements and sending to client
        const cohort = userDoc.cohort || 'JEE Mains';
        const baseTemplate = loadTemplate(cohort);
        userDoc.data = deserializeSyllabus(userDoc.data, baseTemplate);
        
        userDoc.achievements = calculateAchievements(userDoc);
        userDoc.allAchievements = getAllAchievementsStatus(userDoc);

        if (sessionToken) {
          userDoc.sessionToken = sessionToken;
        }
      } else {
        const defaultTemplate = loadTemplate('JEE Mains');
        const defaultSyllabus = deserializeSyllabus(null, defaultTemplate);
        return res.status(200).json({ exists: false, data: defaultSyllabus });
      }
      return res.status(200).json(userDoc);
    } 
    
    if (req.method === 'POST') {
      const { syncId: rawSyncId, data, routines, testLogs, targetDate, cohort, resolvedActivityIds, email, autoBackupEnabled, lastSeenAppVersion, lastSeenExtVersion, userName, themeSettings, deletedAssignmentUrls } = req.body;
      if (!rawSyncId || typeof rawSyncId !== 'string') return res.status(400).json({ error: 'Invalid or missing syncId' });
      const syncId = String(rawSyncId).trim();
      if (!syncId) return res.status(400).json({ error: 'syncId cannot be empty' });

      const userDoc = await resolveUser(db, syncId);
      const isSecure = syncId.startsWith('vny_sec_');

      if (!isSecure && !userDoc) {
        return res.status(400).json({ 
          error: 'Security Enforcement: The Sync ID provided is not secure and does not exist in the database. New sync profiles must be created with a cryptographically secure Sync ID (starts with "vny_sec_") generated by the Vinyas console.' 
        });
      }

      const targetHashedSyncId = userDoc ? userDoc.syncId : hashSyncId(syncId);
      let sessionToken = null;

      if (!userDoc) {
        // This is a first-time registration save with a plaintext Sync ID.
        sessionToken = 'vny_sess_' + crypto.randomBytes(24).toString('hex');
      }

      const docToUse = userDoc || {};
      const activities = docToUse.activities || [];
      const sessions = docToUse.sessions || [];

      if (sessionToken) {
        sessions.push({
          token: sessionToken,
          createdAt: new Date().toISOString(),
          lastUsedAt: new Date().toISOString()
        });
      }

      // Merge existing data (altNames, assignments, books, custom configs) from database to prevent overwriting by old client payloads
      if (userDoc && userDoc.data && Array.isArray(data)) {
        const baseTemplate = loadTemplate(cohort || 'JEE Mains');
        const existingSyllabus = deserializeSyllabus(userDoc.data, baseTemplate);
        
        data.forEach(sub => {
          if (!sub || typeof sub.name !== 'string') return;
          const exSub = existingSyllabus.find(s => s && s.name.trim().toLowerCase() === sub.name.trim().toLowerCase());
          if (exSub) {
            // Merge books
            if (Array.isArray(exSub.books)) {
              if (!sub.books) sub.books = [];
              exSub.books.forEach(exBook => {
                let book = sub.books.find(b => b.url === exBook.url);
                if (!book) {
                  sub.books.push(exBook);
                } else {
                  if (exBook.chapters) {
                    if (!book.chapters) book.chapters = {};
                    Object.keys(exBook.chapters).forEach(chName => {
                      if (!book.chapters[chName]) {
                        book.chapters[chName] = exBook.chapters[chName];
                      }
                    });
                  }
                }
              });
            }

            // Merge chapters progress metadata
            if (Array.isArray(sub.chapters) && Array.isArray(exSub.chapters)) {
              sub.chapters.forEach(ch => {
                if (!ch || typeof ch.name !== 'string') return;
                const exCh = exSub.chapters.find(c => c && c.name.trim().toLowerCase() === ch.name.trim().toLowerCase());
                if (exCh) {
                  // Merge altNames
                  if (Array.isArray(exCh.altNames)) {
                    if (!ch.altNames) ch.altNames = [];
                    exCh.altNames.forEach(name => {
                      if (!ch.altNames.includes(name)) {
                        ch.altNames.push(name);
                      }
                    });
                  }
                  // Merge assignments
                  if (Array.isArray(exCh.assignments)) {
                    if (!ch.assignments) ch.assignments = [];
                    exCh.assignments.forEach(exAss => {
                      // Skip adding back if explicitly deleted by client
                      const normExUrl = normalizeUrl(exAss.url);
                      if (Array.isArray(deletedAssignmentUrls) && deletedAssignmentUrls.some(u => normalizeUrl(u) === normExUrl)) {
                        return;
                      }
                      if (!ch.assignments.some(a => normalizeUrl(a.url) === normExUrl)) {
                        ch.assignments.push(exAss);
                      }
                    });
                  }
                  // Merge custom configs and exercise displays
                  if (exCh.customExerciseConfig && !ch.customExerciseConfig) {
                    ch.customExerciseConfig = exCh.customExerciseConfig;
                  }
                  if (exCh.exerciseDisplayNames && !ch.exerciseDisplayNames) {
                    ch.exerciseDisplayNames = exCh.exerciseDisplayNames;
                  }
                  if (exCh.moduleQuestionStates && Object.keys(exCh.moduleQuestionStates || {}).length > 0) {
                    if (ch.moduleQuestionStates === undefined || ch.moduleQuestionStates === null || Object.keys(ch.moduleQuestionStates || {}).length === 0) {
                      ch.moduleQuestionStates = exCh.moduleQuestionStates;
                    } else {
                      ch.moduleQuestionStates = { ...exCh.moduleQuestionStates, ...ch.moduleQuestionStates };
                    }
                  }
                }
              });
            }
          }
        });
      }

      // Construct a temporary full userDoc to evaluate achievements (using the incoming full data)
      const tempUserDoc = {
        data: data || [],
        routines: routines || [],
        testLogs: testLogs || [],
        activities,
        targetDate: targetDate || null,
        cohort: cohort || 'JEE Mains',
        achievements: docToUse.achievements || []
      };

      const calculatedAchievements = calculateAchievements(tempUserDoc);
      const allAchievements = getAllAchievementsStatus(tempUserDoc);
      // Prune stale deletedAssignmentUrls: only keep URLs that exist in server-side existing data's assignments
      // (since only those could be re-merged). This prevents the list from growing indefinitely.
      let prunedDeletedUrls = deletedAssignmentUrls || [];
      if (userDoc && userDoc.data && Array.isArray(prunedDeletedUrls) && prunedDeletedUrls.length > 0) {
        const baseTemplateForPrune = loadTemplate(cohort || 'JEE Mains');
        const existingSyllabusForPrune = deserializeSyllabus(userDoc.data, baseTemplateForPrune);
        const allExistingAssignmentUrls = new Set();
        existingSyllabusForPrune.forEach(sub => {
          if (!sub || !Array.isArray(sub.chapters)) return;
          sub.chapters.forEach(ch => {
            if (!ch || !Array.isArray(ch.assignments)) return;
            ch.assignments.forEach(a => {
              if (a && a.url) allExistingAssignmentUrls.add(normalizeUrl(a.url));
            });
          });
        });
        prunedDeletedUrls = prunedDeletedUrls.filter(u => allExistingAssignmentUrls.has(normalizeUrl(u)));
      }

      // Serialize the incoming full syllabus data (diff against the base template)
      const baseTemplate = loadTemplate(cohort || 'JEE Mains');
      const serializedData = serializeSyllabus(data || [], baseTemplate);

      const updateDoc = {
        $set: {
          data: serializedData, // Save only the optimized diff structure
          routines: routines || [],
          testLogs: testLogs || [],
          achievements: calculatedAchievements,
          targetDate: targetDate || null,
          cohort: cohort || 'JEE Mains',
          resolvedActivityIds: resolvedActivityIds || [],
          email: email || '',
          autoBackupEnabled: autoBackupEnabled || false,
          sessions,
          deletedAssignmentUrls: prunedDeletedUrls,
          lastUpdated: getISTISOString()
        },
        $unset: {
          logoutTimestamp: "",
          alertSent: ""
        }
      };

      if (lastSeenAppVersion !== undefined) {
        updateDoc.$set.lastSeenAppVersion = lastSeenAppVersion;
      }
      if (lastSeenExtVersion !== undefined) {
        updateDoc.$set.lastSeenExtVersion = lastSeenExtVersion;
      }
      if (userName !== undefined) {
        updateDoc.$set.userName = userName;
      }
      if (themeSettings !== undefined) {
        updateDoc.$set.themeSettings = themeSettings;
      }

      // Sanitize the $set object to remove any keys that are undefined to prevent BSON errors
      if (updateDoc.$set) {
        Object.keys(updateDoc.$set).forEach(key => {
          if (updateDoc.$set[key] === undefined) {
            delete updateDoc.$set[key];
          }
        });
      }

      if (userDoc && userDoc.logoutTimestamp) {
        console.log(`[Vinyas Inactivity] User ${userDoc.syncId} logged active via POST data. Resetting inactivity countdown and warning flags. Previous logoutTimestamp: ${userDoc.logoutTimestamp}`);
      }

      await collection.updateOne({ syncId: targetHashedSyncId }, updateDoc, { upsert: true });

      const responsePayload = { 
        success: true, 
        achievements: calculatedAchievements,
        allAchievements 
      };
      if (sessionToken) {
        responsePayload.sessionToken = sessionToken;
      }
      return res.status(200).json(responsePayload);
    }

    return res.status(405).json({ error: 'Method Not Allowed' });
  } catch (error) {
    console.error(`${getISTLogPrefix()} MongoDB Error in data sync endpoint:`, error);
    return res.status(500).json({ error: error.message });
  }
}
