import crypto from 'crypto';
import { connectToDatabase } from './db.js';
import { calculateAchievements, getAllAchievementsStatus } from './achievements_config.js';
import { getISTISOString, getISTLogPrefix } from './timezone.js';
import { deserializeSyllabus, serializeSyllabus, loadTemplate } from './shared/syllabus.js';
import { resolveUser, hashSyncId } from './shared/auth.js';

export default async function handler(req, res) {
  // Enforce global request body size limit of 2MB to protect MongoDB and Vercel functions
  const contentLength = req.headers['content-length'] ? parseInt(req.headers['content-length'], 10) : 0;
  if (contentLength > 2 * 1024 * 1024 || (req.body && JSON.stringify(req.body).length > 2 * 1024 * 1024)) {
    return res.status(413).json({ error: 'Payload too large (limit is 2MB)' });
  }

  try {
    const db = await connectToDatabase();
    const collection = db.collection('users');

    if (req.method === 'GET') {
      const rawSyncId = req.query.syncId;
      if (!rawSyncId || typeof rawSyncId !== 'string') {
        return res.status(400).json({ error: 'Invalid or missing syncId' });
      }
      const syncId = String(rawSyncId).trim();
      if (!syncId) return res.status(400).json({ error: 'syncId cannot be empty' });

      const userDoc = await resolveUser(db, syncId);
      let sessionToken = null;

      if (userDoc) {
        if (userDoc.logoutTimestamp) {
          console.log(`[Vinyas Inactivity] User ${userDoc.syncId} logged back in / active. Resetting inactivity countdown and warning flags. Previous logoutTimestamp: ${userDoc.logoutTimestamp}`);
        }
        // Clear logout status because user is active
        await collection.updateOne({ syncId: userDoc.syncId }, { $unset: { logoutTimestamp: "", alertSent: "" } });
        userDoc.logoutTimestamp = null;
        userDoc.alertSent = false;
        
        // If lookup was done via a plaintext syncId, generate a new session token
        if (syncId.startsWith('vny_sec_')) {
          sessionToken = 'vny_sess_' + crypto.randomBytes(24).toString('hex');
          const newSession = {
            token: sessionToken,
            createdAt: new Date().toISOString(),
            lastUsedAt: new Date().toISOString()
          };
          await collection.updateOne(
            { syncId: userDoc.syncId },
            { $push: { sessions: newSession } }
          );
        }

        // Reconstruct the full syllabus data before calculating achievements and sending to client
        const baseTemplate = loadTemplate(userDoc.cohort);
        userDoc.data = deserializeSyllabus(userDoc.data, baseTemplate);
        
        userDoc.achievements = calculateAchievements(userDoc);
        userDoc.allAchievements = getAllAchievementsStatus(userDoc);

        if (sessionToken) {
          userDoc.sessionToken = sessionToken;
        }
      }
      return res.status(200).json(userDoc || { exists: false });
    } 
    
    if (req.method === 'POST') {
      const { syncId: rawSyncId, data, routines, testLogs, targetDate, cohort, resolvedActivityIds, email, autoBackupEnabled, lastSeenAppVersion, lastSeenExtVersion, userName } = req.body;
      if (!rawSyncId || typeof rawSyncId !== 'string') return res.status(400).json({ error: 'Invalid or missing syncId' });
      const syncId = String(rawSyncId).trim();
      if (!syncId) return res.status(400).json({ error: 'syncId cannot be empty' });

      const userDoc = await resolveUser(db, syncId);
      const isSecure = syncId.startsWith('vny_sec_');

      if (!isSecure && !userDoc) {
        return res.status(400).json({ 
          error: 'Security Enforcement: The Sync ID provided is not secure and does not exist in the database. New sync profiles must be created with a cryptographically secure Sync ID (starts with "vny_sec_") generated by the Vinyas console.' 
        });
      }

      const targetHashedSyncId = userDoc ? userDoc.syncId : hashSyncId(syncId);
      let sessionToken = null;

      if (!userDoc) {
        // This is a first-time registration save with a plaintext Sync ID.
        sessionToken = 'vny_sess_' + crypto.randomBytes(24).toString('hex');
      }

      const docToUse = userDoc || {};
      const activities = docToUse.activities || [];
      const sessions = docToUse.sessions || [];

      if (sessionToken) {
        sessions.push({
          token: sessionToken,
          createdAt: new Date().toISOString(),
          lastUsedAt: new Date().toISOString()
        });
      }

      // Construct a temporary full userDoc to evaluate achievements (using the incoming full data)
      const tempUserDoc = {
        data,
        routines,
        testLogs,
        activities,
        targetDate,
        cohort,
        achievements: docToUse.achievements || []
      };

      const calculatedAchievements = calculateAchievements(tempUserDoc);
      const allAchievements = getAllAchievementsStatus(tempUserDoc);

      // Serialize the incoming full syllabus data (diff against the base template)
      const baseTemplate = loadTemplate(cohort);
      const serializedData = serializeSyllabus(data, baseTemplate);

      const updateDoc = {
        $set: {
          data: serializedData, // Save only the optimized diff structure
          routines,
          testLogs,
          achievements: calculatedAchievements,
          targetDate,
          cohort,
          resolvedActivityIds,
          email,
          autoBackupEnabled,
          sessions,
          lastUpdated: getISTISOString()
        },
        $unset: {
          logoutTimestamp: "",
          alertSent: ""
        }
      };

       if (lastSeenAppVersion !== undefined) {
        updateDoc.$set.lastSeenAppVersion = lastSeenAppVersion;
      }
      if (lastSeenExtVersion !== undefined) {
        updateDoc.$set.lastSeenExtVersion = lastSeenExtVersion;
      }
      if (userName !== undefined) {
        updateDoc.$set.userName = userName;
      }

      if (userDoc && userDoc.logoutTimestamp) {
        console.log(`[Vinyas Inactivity] User ${userDoc.syncId} logged active via POST data. Resetting inactivity countdown and warning flags. Previous logoutTimestamp: ${userDoc.logoutTimestamp}`);
      }

      await collection.updateOne({ syncId: targetHashedSyncId }, updateDoc, { upsert: true });

      const responsePayload = { 
        success: true, 
        achievements: calculatedAchievements,
        allAchievements 
      };
      if (sessionToken) {
        responsePayload.sessionToken = sessionToken;
      }
      return res.status(200).json(responsePayload);
    }

    return res.status(405).json({ error: 'Method Not Allowed' });
  } catch (error) {
    console.error(`${getISTLogPrefix()} MongoDB Error in data sync endpoint:`, error);
    return res.status(500).json({ error: error.message });
  }
}
